### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by TireStraits** [zoedsoupe/supabase-ex#39]
Maybe say whether to set up env variables as a system variable or a .env, either way, `supabase_base_url: System.fetch_env!` doesn't work on macos even if you do export SUPABASE_URL=theurlthatyouhave, im assuming its a system variable from System.fetch, but since it doesnt work idk.

example url, error i get when i put my real url:
`** (System.EnvError) could not fetch environment variable "EXAMPLEURL" because it is not set`

thanks!

**Comment by zoedsoupe** [comment]
Hello! show you set the `.env` up? in general, for environment variables to work in the shell (bash, zsh or csh) you need to **export** them as:
```sh
export SUPABASE_URL=http://localhost:54321
```

setting the `.env` content as above and then `source .env` in your shell, now the env variables will be available. Elixir doesn't read `.env` files automatically, so you need to source them or use a [dotenv package](https://hex.pm/packages?search=dotenv&sort=recent_downloads)

**Comment by TheCriticalGamer** [comment]
I tried it by shell, I didn't know how to use the dotenv package, I'm super new to elixir, I only know simple syntax.

**Comment by zoedsoupe** [comment]
I mean, in general in Elixir we don't use dot env packages, you can just define a `.env` file, like this:

```bash
export SUPABASE_URL=https://your-supabase-project-url
export SUPABASE_KEY=supabase-token
```

Then on your terminal you can safely use `source .env` command, considering that you're using a bash compatible shell (bash, zsh)

Then, starting an `iex` session on your project:
`iex -S mix`

Then:
```elixir
iex> System.get_env "SUPABASE_URL"
iex> https://your-supabase-project-url
```

**Comment by zoedsoupe** [comment]
If you're so new to Elixir environment, then you should take a look into the official language documentation and getting started guides: https://hexdocs.pm/elixir/introduction.html
