### ISSUE TITLE
could not compile dependency :supabase_gotrue

### ISSUE THREAD

**Issue by sergiotapia** [zoedsoupe/supabase-ex#43]
I added the deps to mix.exs

```
{:supabase_potion, "~> 0.4"},
{:supabase_storage, "~> 0.3"},
{:supabase_gotrue, "~> 0.3"}
```

Added the config to `runtime.exs`

```
config :supabase_potion,
  manage_clients: true,
  supabase_base_url: System.get_env("SUPABASE_URL"),
  supabase_api_key: System.get_env("SUPABASE_KEY")
```

And when I run `iex -S mix phx.server` I get this error:

> ==> supabase_gotrue
> Compiling 29 files (.ex)
> 
> == Compilation error in file lib/supabase/go_true/plug.ex ==
> ** (ArgumentError) could not fetch application environment :authentication_client for application :supabase_gotrue because the application was not loaded nor configured
>     (elixir 1.16.2) lib/application.ex:638: Application.compile_env!/3
>     lib/supabase/go_true/plug.ex:38: (module)
> could not compile dependency :supabase_gotrue, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile supabase_gotrue --force", update it with "mix deps.update supabase_gotrue" or clean it with "mix deps.clean supabase_gotrue"

**Comment by zoedsoupe** [comment]
Hello! thank you for the issue! Yeah... it happens that `supabase_gotrue` expects some configuration options that aren't very well documented, so you receive this compile error.

I'm refactoring documentation for all supabase elixir client libraries and also building some phoenix sample applications

**Comment by zoedsoupe** [comment]
Also the version `0.4.1` of `supabase_potion` introduce one off clients, that aren't modules necessarily... Given that `supabase_gotrue` expect a module client to be defined, to use for Live View hooks and Plugs

I'll solve this issue right now and publish a new release with fixes!

**Comment by sergiotapia** [comment]
To fix I had to add some stuff to both runtime.exs and config.exs - I figured this out by reading the sourcecode for supabase potion and gotrue. Hope this helps you improve the docs. Thank you for the library!

```
# runtime.exs
config :supabase_potion,
  supabase_url: System.get_env("SUPABASE_BASE_URL"),
  supabase_key: System.get_env("SUPABASE_API_KEY"),
  supabase_base_url: System.get_env("SUPABASE_BASE_URL"),
  supabase_api_key: System.get_env("SUPABASE_API_KEY")

# config.exs
config :supabase_gotrue,
  authentication_client: :myapp_supabase,
  endpoint: MyAppWeb.Endpoint

# Then in a Plug I can receive a supabase user token to auth and fetch the user.
# Authorization: Bearer sometoken123
alias Supabase.GoTrue
client = Supabase.init_client!()
{:ok, user} = GoTrue.get_user(client, %GoTrue.Session{access_token: "sometoken123"})
```

**Comment by zoedsoupe** [comment]
Yeah, basically is that! I just launched a release (https://hexdocs.pm/supabase_gotrue/0.3.9/readme.html#usage) that simplifies the usage and configuration options! And now strange compilation errors without documentation or description would not occur anymore.
